"""Build the browser HTML for duplicate review."""
from __future__ import annotations
import html,json
from review_data import human_size

def build_page(report,groups)->str:
    sections=[]
    for no in sorted(groups):
        cards=[];g=groups[no]
        for x in g:
            p=x['path'];badge='Suggested KEEP' if x['keeper'] else x['tag'];cls='keep' if x['keeper'] or x['tag']=='KEEP' else 'dup'
            media=f'<video controls preload="metadata" src="/media/{x["id"]}"></video>' if x['exists'] else '<div class="missing">File is missing</div>'
            check=f'<label><input class="del" type="checkbox" data-id="{x["id"]}" data-keeper="{str(x["keeper"]).lower()}"> Mark for delete</label>' if x['exists'] else '<span class="muted">Cannot process</span>'
            openb=f'<button onclick="openFolder(\'{x["id"]}\')">Open folder</button>' if x['exists'] else ''
            cards.append(f'<article class="card" data-card="{x["id"]}"><div class="badge {cls}">{html.escape(badge)}</div>{media}<div class="info"><div class="name">{html.escape(p.name)}</div><div class="meta">{human_size(p)}</div><div class="path">{html.escape(str(p.parent))}</div><div class="actions">{check}{openb}</div></div></article>')
        dup=json.dumps([x['id'] for x in g if x['exists'] and x['tag']=='DUP?' and not x['keeper']]);allids=json.dumps([x['id'] for x in g if x['exists']])
        sections.append(f'<section class="group"><div class="head"><div><h2>Duplicate Group {no}</h2><span class="muted">{len(g)} files</span></div><div><button onclick=\'selectIds({dup})\'>Mark DUP? files</button> <button onclick=\'clearIds({allids})\'>Clear group</button></div></div><div class="grid">{"".join(cards)}</div></section>')
    return PAGE.replace('{{REPORT}}',html.escape(str(report))).replace('{{SECTIONS}}',''.join(sections))

PAGE='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Duplicate Video Review</title><style>
body{margin:0;background:#0d1117;color:#e6edf3;font-family:Segoe UI,Arial}header{position:sticky;top:0;z-index:9;background:#0d1117ee;border-bottom:1px solid #30363d;padding:14px 20px}.top{max-width:1700px;margin:auto;display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}main{max-width:1700px;margin:auto;padding:20px}h1,h2{margin:0}button{background:#21262d;color:#e6edf3;border:1px solid #30363d;border-radius:7px;padding:8px 11px;cursor:pointer}.danger{background:#da3633}.notice{border-left:4px solid #d29922;background:#161b22;padding:12px;margin-bottom:18px}.group{background:#161b22;border:1px solid #30363d;border-radius:10px;margin-bottom:24px;overflow:hidden}.head{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap;padding:13px;border-bottom:1px solid #30363d}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:13px;padding:13px}.card{position:relative;background:#1f2630;border:1px solid #30363d;border-radius:9px;overflow:hidden}.card.selected{outline:3px solid #f85149;outline-offset:-3px}video,.missing{display:block;width:100%;aspect-ratio:16/9;background:#000}.missing{display:grid;place-items:center;color:#f85149}.badge{position:absolute;top:8px;left:8px;z-index:2;padding:5px 8px;border-radius:999px;font-weight:700}.keep{background:#3fb950;color:#07130a}.dup{background:#d29922;color:#151006}.info{padding:11px}.name{font-weight:700;overflow-wrap:anywhere}.meta{color:#58a6ff;font-size:13px}.path,.muted{color:#8b949e;font-size:12px;overflow-wrap:anywhere}.actions{display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap;border-top:1px solid #30363d;margin-top:10px;padding-top:10px}label{color:#ffb3ad;font-weight:650}</style></head><body><header><div class="top"><div><h1>Duplicate Video Review</h1><div class="muted">{{REPORT}}</div></div><div><span id="status">0 marked</span> <button onclick="clearAll()">Clear all</button> <button class="danger" onclick="processSelected()">Process Selected</button></div></div></header><main><div class="notice"><b>Safety:</b> files go to Recycle Bin. The app blocks deleting every file in a group.</div>{{SECTIONS}}</main><script>
function refresh(){let n=0;document.querySelectorAll('.del').forEach(b=>{let c=document.querySelector(`[data-card="${b.dataset.id}"]`);if(b.checked){n++;c?.classList.add('selected')}else c?.classList.remove('selected')});document.getElementById('status').textContent=n+' marked'}document.addEventListener('change',e=>{if(e.target.classList.contains('del'))refresh()});function selectIds(ids){ids.forEach(id=>{let b=document.querySelector(`.del[data-id="${id}"]`);if(b)b.checked=true});refresh()}function clearIds(ids){ids.forEach(id=>{let b=document.querySelector(`.del[data-id="${id}"]`);if(b)b.checked=false});refresh()}function clearAll(){document.querySelectorAll('.del').forEach(b=>b.checked=false);refresh()}async function openFolder(id){let r=await fetch('/open-folder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});let d=await r.json();if(!d.ok)alert(d.message)}async function processSelected(){let bs=[...document.querySelectorAll('.del:checked')];if(!bs.length)return alert('Nothing marked.');let k=bs.some(b=>b.dataset.keeper==='true');if(!confirm(`Move ${bs.length} selected file(s) to Recycle Bin?`+(k?'\\nWARNING: Suggested KEEP selected.':'')))return;if(k&&!confirm('Confirm Suggested KEEP selection again.'))return;let r=await fetch('/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:bs.map(b=>b.dataset.id)})});let d=await r.json();alert(`Moved: ${d.processed||0}\\nFailed: ${d.failed||0}\\nBlocked: ${(d.blocked||[]).length}`);location.reload()}refresh();
</script></body></html>'''
